name: _Build

on:
  workflow_call:
    inputs:
      browser:
        required: true
        type: string
        description: "Target browser: chrome or firefox"

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 23
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build:${{ inputs.browser }}

      - name: Rename dist folder
        run: |
          mv dist-${{ inputs.browser }} anime4k-webextension-plus

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anime4k-webextension-plus-${{ inputs.browser }}
          path: anime4k-webextension-plus
