name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [labeled]

jobs:
  build-chrome:
    uses: ./.github/workflows/_build.yml
    with:
      browser: chrome
    permissions:
      contents: read
      actions: write

  build-firefox:
    uses: ./.github/workflows/_build.yml
    with:
      browser: firefox
    permissions:
      contents: read
      actions: write
